version: "3.9"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  data-pipeline-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-pipeline:latest
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
